import pygame

KEY_ANY = -1
KEY_BACKSPACE = pygame.K_BACKSPACE
KEY_TAB = pygame.K_TAB
KEY_CLEAR = pygame.K_CLEAR
KEY_RETURN = pygame.K_RETURN
KEY_PAUSE = pygame.K_PAUSE
KEY_ESCAPE = pygame.K_ESCAPE
KEY_SPACE = pygame.K_SPACE
KEY_EXCLAIM = pygame.K_EXCLAIM
KEY_QUOTEDBL = pygame.K_QUOTEDBL
KEY_HASH = pygame.K_HASH
KEY_DOLLAR = pygame.K_DOLLAR
KEY_AMPERSAND = pygame.K_AMPERSAND
KEY_QUOTE = pygame.K_QUOTE
KEY_LEFTPAREN = pygame.K_LEFTPAREN
KEY_RIGHTPAREN = pygame.K_RIGHTPAREN
KEY_ASTERISK = pygame.K_ASTERISK
KEY_PLUS = pygame.K_PLUS
KEY_COMMA = pygame.K_COMMA
KEY_MINUS = pygame.K_MINUS
KEY_PERIOD = pygame.K_PERIOD
KEY_SLASH = pygame.K_SLASH
KEY_0 = pygame.K_0
KEY_1 = pygame.K_1
KEY_2 = pygame.K_2
KEY_3 = pygame.K_3
KEY_4 = pygame.K_4
KEY_5 = pygame.K_5
KEY_6 = pygame.K_6
KEY_7 = pygame.K_7
KEY_8 = pygame.K_8
KEY_9 = pygame.K_9
KEY_COLON = pygame.K_COLON
KEY_SEMICOLON = pygame.K_SEMICOLON
KEY_LESS = pygame.K_LESS
KEY_EQUALS = pygame.K_EQUALS
KEY_GREATER = pygame.K_GREATER
KEY_QUESTION = pygame.K_QUESTION
KEY_AT = pygame.K_AT
KEY_LEFTBRACKET = pygame.K_LEFTBRACKET
KEY_BACKSLASH = pygame.K_BACKSLASH
KEY_RIGHTBRACKET = pygame.K_RIGHTBRACKET
KEY_CARET = pygame.K_CARET
KEY_UNDERSCORE = pygame.K_UNDERSCORE
KEY_BACKQUOTE = pygame.K_BACKQUOTE
KEY_A = pygame.K_a
KEY_B = pygame.K_b
KEY_C = pygame.K_c
KEY_D = pygame.K_d
KEY_E = pygame.K_e
KEY_F = pygame.K_f
KEY_G = pygame.K_g
KEY_H = pygame.K_h
KEY_I = pygame.K_i
KEY_J = pygame.K_j
KEY_K = pygame.K_k
KEY_L = pygame.K_l
KEY_M = pygame.K_m
KEY_N = pygame.K_n
KEY_O = pygame.K_o
KEY_P = pygame.K_p
KEY_Q = pygame.K_q
KEY_R = pygame.K_r
KEY_S = pygame.K_s
KEY_T = pygame.K_t
KEY_U = pygame.K_u
KEY_V = pygame.K_v
KEY_W = pygame.K_w
KEY_X = pygame.K_x
KEY_Y = pygame.K_y
KEY_Z = pygame.K_z
KEY_DELETE = pygame.K_DELETE

KEY_UP = pygame.K_UP
KEY_DOWN = pygame.K_DOWN
KEY_LEFT = pygame.K_LEFT
KEY_RIGHT = pygame.K_RIGHT
KEY_INSERT = pygame.K_INSERT
KEY_HOME = pygame.K_HOME
KEY_END = pygame.K_END
KEY_PAGEUP = pygame.K_PAGEUP
KEY_PAGEDOWN = pygame.K_PAGEDOWN

KEY_F1 = pygame.K_F1
KEY_F2 = pygame.K_F2
KEY_F3 = pygame.K_F3
KEY_F4 = pygame.K_F4
KEY_F5 = pygame.K_F5
KEY_F6 = pygame.K_F6
KEY_F7 = pygame.K_F7
KEY_F8 = pygame.K_F8
KEY_F9 = pygame.K_F9
KEY_F10 = pygame.K_F10
KEY_F11 = pygame.K_F11
KEY_F12 = pygame.K_F12

MOUSE_LEFT = 1
MOUSE_MIDDLE = 2
MOUSE_RIGHT = 3
MOUSE_SCROLL_UP = 4
MOUSE_SCROLL_DOWN = 5

WHITE       = (255, 255, 255)
BLACK       = (0, 0, 0)
RED         = (255, 0, 0)
GREEN       = (0, 255, 0)
BLUE        = (0, 0, 255)
YELLOW      = (255, 255, 0)
CYAN        = (0, 255, 255)
MAGENTA     = (255, 0, 255)
ORANGE      = (255, 165, 0)
PURPLE      = (128, 0, 128)
PINK        = (255, 192, 203)
BROWN       = (165, 42, 42)
GREY        = (128, 128, 128)
LIGHT_GREY  = (200, 200, 200)
DARK_GREY   = (50, 50, 50)
LIGHT_BLUE  = (173, 216, 230)
DARK_BLUE   = (0, 0, 139)
LIGHT_GREEN = (144, 238, 144)
DARK_GREEN  = (0, 100, 0)

START   = 1
CENTER  = 2
END     = 3